In [1]:
# day 3 recap
#1.  numpy creation, zeros, ones, arange, linspace, random.rand
#2.  indexing, slicing, masking, fancy slicing np[[row],[col]]
#3.  broadcasting (3,1) + (1,4) = (3,4)

In [2]:
import numpy as np

In [3]:
#1. Create a 4x5 array using arange and reshape
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
#2.Slice the last column
a[:,-1]

array([ 5, 10, 15, 20])

In [5]:
#3. Boolean mask — get all values greater than 10
mask = a[a>10]
print(mask)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
#4. Broadcasting — add np.array([1,2,3,4,5]) to your array
b = np.array([1, 2, 3, 4, 5])

#a + b -> b(5,) -> just a 1D array of 5 elements, no concept of rows or column
#its treated like (1,5) -> then stretched to (5,5)

print(a,"\n")
print(b,"\n")
print(a+b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[1 2 3 4 5] 

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]]


# Day 4

- Vectorised operations: replace every for-loop with a NumPy op
- Linear algebra: dot product, matrix multiply (@), transpose, inverse
- Implement cosine similarity between two vectors from scratch


In [7]:
c = np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Task 1:Vectorised operations: replace every for-loop with a NumPy op
# replace these loops with ONE NumPy line each

#a. Loop version 1 — square every element
result = []
for x in c:
  result.append(x**2)

#numpy
print("Square",np.square(c))

#b.  Loop version 2 — sum of all elements
total = 0
for x in a:
    total += x

#numpy vectorised operation
print("Sum: ",np.sum(c))

#c. Loop version 3 — multiply two arrays element by element
d = np.arange(11,21)
result= []
for i in range(len(a)):
  result.append(a[i] * b[i])
#numpy
print("a * b : ",c*d)


Square [  1   4   9  16  25  36  49  64  81 100]
Sum:  55
a * b :  [ 11  24  39  56  75  96 119 144 171 200]


In [9]:
#time to check the differrence between loops and numpy
import time

#time for loop
start = time.time()
result = [x**2 for x in range(100000)]
print(f"Loop: {time.time() - start:.4f}s")


#time numpy version
e = np.arange(100000)
start = time.time()
result= np.square(c)
print(f"NumPy: {time.time()-start:.4f}s")

Loop: 0.0116s
NumPy: 0.0023s


In [10]:
#Task 2: Linear algebra: dot product, matrix multiply (@), transpose, inverse
#a. Transpose
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])

print(a1)
#transpose
print("Transpose\n",a1.T)

[[1 2]
 [3 4]]
Transpose
 [[1 3]
 [2 4]]


In [11]:
#dot product
print(np.dot(a1,b1))

[[19 22]
 [43 50]]


In [12]:
#matrix multiply

# Weights × inputs in neural networks = @ matrix multiply
# Applying a mask or scaling = * element-wise

print(a1 @ b1,"\n")
print(a1*b1)

[[19 22]
 [43 50]] 

[[ 5 12]
 [21 32]]


In [13]:
#INVERSE
from numpy.linalg import inv
ainv = inv(a1)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
print("A X A-1\n",np.round(a1 @ ainv))

A X A-1
 [[1. 0.]
 [0. 1.]]


In [15]:
#Task 3:Implement cosine similarity between two vectors from scratch
#Cosine similarity measures how similar two vectors are. Used everywhere in ML — NLP, recommendation systems, search engines

#Formula:
'''
cos(θ) = (A · B) / (||A|| × ||B||)

'''
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

magnitudeA = np.square(v1)
print(magnitudeA)

magnitudeA_ = np.sqrt(np.sum(np.square(v1)))
print(magnitudeA_)


magnitudeB_ = np.sqrt(np.sum(np.square(v2)))
print(magnitudeB_)

[1 4 9]
3.7416573867739413
8.774964387392123


In [16]:
cosine = (np.dot(v1,v2))/(magnitudeA_ * magnitudeB_)
print(cosine)

0.9746318461970762


In [17]:
def cosine_similarity(v1, v2):
  magnitudeA_ = np.sqrt(np.sum(np.square(v1)))
  magnitudeB_ = np.sqrt(np.sum(np.square(v2)))

  cosine = (np.dot(v1,v2))/(magnitudeA_ * magnitudeB_)
  return cosine


In [18]:
# coded version
print(np.sqrt(np.sum(np.square(v1))))

# numpy version
print(np.linalg.norm(v1))

3.7416573867739413
3.7416573867739413


In [19]:
def cosine_similarity_(v1,v2):
  magnitudeA_ = np.linalg.norm(v1)
  magnitudeB_ = np.linalg.norm(v2)

  cosine = (np.dot(v1,v2))/(magnitudeA_ * magnitudeB_)
  return cosine
