 ## Quick Week 1 recall
 1. Create a 4x5 NumPy array and slice the last two columns
 2. Boolean mask — values greater than 10
 3. Write my_mean() from scratch

In [ ]:
import numpy as np

In [ ]:
#  1. Create a 4x5 NumPy array and slice the last two columns
a = np.arange(1,21).reshape(4,5)
print(a)

#last 2 cols
print(a[:,-2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [ ]:
#2. Boolean mask — values greater than 10
mask10 = a[a>10]
print(mask10)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#3. Write my_mean() from scratch
def my_mean(arr):

  mean = np.sum(arr) / arr.size

  return mean
my_mean(a)

np.float64(10.5)

# Week 2 Day 1

	1. Pandas Series vs DataFrame: indexing with iloc, loc, boolean masking
	2. read_csv, read_json — load the Titanic dataset
	3. describe(), info(), value_counts() — understand your data before doing anything else


In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
print(df.shape)

(891, 12)


	1. Pandas Series vs DataFrame: indexing with iloc, loc, boolean masking

In [ ]:
#dataframe - the whole table
print(type(df))

#series one column
print(type(df['Survived']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
#indexing with iloc, loc

#iloc - indexing by position(number)
#first row
print(df.iloc[0])
print("\n-------------------\n")

## first 3 rows, first 3 cols
print(df.iloc[0:3,0:3])

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

-------------------

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3


In [ ]:
#loc - indexing by labels (column names)

# row-0 , col -Name
print(df.loc[0,'Name'])

print("\n-------------------\n")

# rows 0-2, specific columns
print(df.loc[0:2,['Name','Age']])

## loc → inclusive end → loc[0:2] gives rows 0,1,2
## iloc → exclusive end (like Python slicing) → iloc[0:3] gives rows 0,1,2

Braund, Mr. Owen Harris

-------------------

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0


In [ ]:
# boolean masking

#1. Get all passengers who survived
#2. Get all female passengers over 30
#3. Get only the Name and Age columns for passengers in first class

#1. Get all passengers who survived
surv = df[df.Survived==1]
print(surv)
print("\n-------------------\n")





     PassengerId  Survived  Pclass  \
0              1         1       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         1       3   
..           ...       ...     ...   
886          887         1       2   
887          888         1       1   
888          889         1       3   
889          890         1       1   
890          891         1       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [ ]:
#2. Get all female passengers over 30
female30 = df[(df.Sex=='female') & (df.Age>30)]
print(female30)
print("\n-------------------\n")

     PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
11            12         1       1   
15            16         1       2   
18            19         1       3   
..           ...       ...     ...   
862          863         1       1   
865          866         1       2   
871          872         1       1   
879          880         1       1   
885          886         1       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
..                                                 ...     ...   ... 

In [ ]:
#3. 3. Get only the Name and Age columns for passengers in first class
firstclass = df[df['Pclass']==1]
print(firstclass.loc[:,['Name','Age']])

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
23                        Sloper, Mr. William Thompson  28.0
..                                                 ...   ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
872                           Carlsson, Mr. Frans Olof  33.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
887                       Graham, Miss. Margaret Edith  19.0
889                              Behr, Mr. Karl Howell  26.0

[216 rows x 2 columns]


In [ ]:
first = df.loc[df['Pclass']==1,['Name','Age']]
first

,Name,Age
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0
6,"McCarthy, Mr. Timothy J",54.0
11,"Bonnell, Miss. Elizabeth",58.0
23,"Sloper, Mr. William Thompson",28.0
...,...,...
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0
872,"Carlsson, Mr. Frans Olof",33.0
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0
887,"Graham, Miss. Margaret Edith",19.0




	2. read_csv, read_json — load the Titanic dataset

In [ ]:
#store in json and read it back
df.head(5).to_json("titanic.json")

#read json
df_json = pd.read_json("titanic.json")
print(df_json)
print(df.head(5))

   PassengerId  Survived  Pclass  \
0            1         1       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         1       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  None        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  None        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  None        S  
   Passe


    3.  describe(), info(), value_counts() — understand your data before doing anything else

In [ ]:
# Task  — understand your data:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df['Survived'].value_counts()

,count
Survived,
0,549
1,342


Day 1 done ------------------------------------------------------------------

In [ ]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [ ]:
df['Pclass']

,Pclass
0,3
1,1
2,3
3,1
4,3
...,...
886,2
887,1
888,3
889,1
